import type { ProcedureFormValues } from "@/components/principal/schemas/schema";

export const stepFields = {
  step1: [
    "ruc",
    "policeReportNumber",
    "procedureType",
    "formalizationDate",
    "policeReportDate",
    "policeStation",
    "comuna",
    "crime",
    "prosecutor",
    "detaineesCount",
  ] satisfies (keyof ProcedureFormValues)[],

  step2: [
    "cocaineGrams",
    "marijuanaGrams",
    "cocaineBaseGrams",
    "marijuanaPlantsUnits",
    "medicineType",
    "medicineWeightGrams",
    "otherDrugType",
    "otherDrugWeightGrams",
    "vehiclesUnits",
    "moneyAmount",
    "foreignMoneyAmount",
    "seizedProperty",
  ] satisfies (keyof ProcedureFormValues)[],

  step3: [
    "pistolsUnits",
    "revolverUnits",
    "homemadeGunUnits",
    "adaptedBlankGunUnits",
    "blankGunUnits",
    "shotgunUnits",
    "ammoUnits",
    "magazinesUnits",
    "rifleUnits",
    "assaultRifleUnits",
    "carbineUnits",
    "airgunUnits",
    "fantasyWeaponUnits",
    "grenadeUnits",
    "submachinegunUnits",
    "suppressorUnits",
    "antiTankShellUnits",
    "tearGasBombUnits",
    "molotovUnits",
    "fireworksUnits",
  ] satisfies (keyof ProcedureFormValues)[],
};
